import '../styles/globals.css'

import React from 'react'

import type { Metadata } from 'next'

import { fontRoboto } from '~/libs/fonts'

import { Provider } from '~/components/Provider'

export const metadata: Metadata = {
  title: 'converter',
  description: 'Generated by create next app'
}

interface RootLayoutProps {
  children: React.ReactNode
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="pt-br" className={fontRoboto.variable} suppressHydrationWarning>
      <body>
        <Provider>
          <>{children}</>
        </Provider>
      </body>
    </html>
  )
}

export default RootLayout
